### ISSUE TITLE
2.0.1+nexus.1, Ziggo Go not working.

### ISSUE THREAD

**Issue by Laurvin** [3DSBricker/dut-iptv#5] opened 2023-09-10 20:27 UTC
I uninstalled all previous versions.

Then I installed the new version from QuasarKodearring (dated ‎Sunday, ‎10 ‎September ‎2023, ‏‎15:27:36).

After installing Ziggo Go from the Dutch IPTV Repository it shows up but when I click it, it doesn't open anything but goes to my default Videos screen.

**Comment by 3DSBricker** [comment] 2023-09-11 08:53
Hello Laurvin,
I can confirm this issue myself using an Nvidia Shield. I will look into it. Oddly enough, it works perfectly on any Windows based Kodi version.

**Comment by 3DSBricker** [comment] 2023-09-11 10:19
It should be fixed now. You can simply reinstall the add-on, if that doesn't help, just remove it and restart Kodi. You can install it afterwards. It should work fine again.

**Comment by 3DSBricker** [comment] 2023-09-11 13:25
In that case, could you uninstall all again, exit Kodi, and then go to `%appdata%/Kodi/addons/packages` and delete:
`plugin.video.ziggo-2.0.1 nexus.1.zip` and `service.dutiptv.proxy-2.0.1 nexus.1.zip`
Afterwards, restart Kodi and install the repository and the addon again.

**Comment by Laurvin** [comment] 2023-09-11 15:13
That did the trick, install-wise!

However... when I try to go to Replay TV and try and open any day on any channel I get this error:
![Clipboard01](https://github.com/3DSBricker/dut-iptv/assets/28167771/38abb970-e6ac-4153-a3c1-25c64abf6abe)

I have the basic Ziggo subscription but I don't think that should matter as I am able to watch replay programs via the ZiggoGo website. I went to the site right now and was able to watch the 14:00 Journaal on NPO1 without any issue.

**Comment by 3DSBricker** [comment] 2023-09-11 16:28
Yes, unfortunately replay TV does not work due to the lack of a working EPG. This always was managed by Dut-EPG, but it stopped 01-01-2023. I assume this was an automated process that simply reached its end, and without the original developer, I have no way of knowing how they made the EPG on Github. In your case, only Live TV is possible. Recordings do work, but I don't think your subscription has them. If they do, you can use that.

**Comment by Laurvin** [comment] 2023-09-11 16:37
Ah, I did read something about this in the patch notes but I guess I forgot immediately. :p

Anyway, thanks for all the help, glad to see at least some parts can be made to work again!

**Comment by 3DSBricker** [comment] 2023-09-11 18:08
Yes, I'm trying to at least restore all basic functions. Unfortunately without EPG, everything related to or based on replay does not work. Including VOD. (some work, though, like some with KPN due to not requiring the EPG or having old entries that are in the EPG)

**Closed** 2023-09-18 14:33 UTC
Labels: bug
